New template

diff --git a/check_instance_up b/check_instance_up
--- a/check_instance_up
+++ b/check_instance_up
@@ -26,10 +26,8 @@
 # if the file has tabs instead of spaces, it could fail to find the instance
 # name.
 #
-# Here comes the documentation
-#
 # Parameters:
-# -d | --directory : Home directory of the instance. Usually it is 
+# -i | --instance : Home directory of the instance. Usually it is
 #   /home/db2inst1
 # -h | --help : Show the help of this script.
 # -V | --version : Show the current version of this script.
@@ -39,35 +37,22 @@
 #
 # 0 The plugin was able to check the service and it appeared to be functioning
 #   properly.
-# 1 The plugin was able to check the service, but it appeared to be above some 
+# 1 The plugin was able to check the service, but it appeared to be above some
 #   "warning" threshold or did not appear to be working properly.
 # 2 The plugin detected that either the service was not running or it was above
 #   some "critical" threshold.
 # 3 Invalid command line arguments were supplied to the plugin or low-level
 #   failures internal to the plugin (such as unable to fork, or open a tcp
-#   socket) that prevent it from performing the specified operation. 
+#   socket) that prevent it from performing the specified operation.
 #   Higher-level errors (such as name resolution errors, socket timeouts, etc)
 #   are outside of the control of plugins and should generally NOT be reported
-#   as UNKNOWN states. 
+#   as UNKNOWN states.
 #
 # Author: Andres Gomez Casanova
 # Version: v1.0 2013-01-18
 
 # Flag for debugging.
 #set -xv
-
-# Nagios return codes
-OK=0
-WARNING=1
-CRITICAL=2
-UNKNOWN=3
-
-# Nagios Output
-# Text output 80 chars | Optional Perf Data Line 1
-# Long text Line 1
-# Long text Line 2 | Optional Perf Data Line 2
-# Optional Perf Data Line 3
-OUTPUT=
 
 # Version of this script.
 function print_revision {
@@ -83,90 +68,128 @@ function print_help {
   print_usage $1
   # Max 80 chars width.
   echo "This scripts checks if the instance is active by querying netstats."
-  echo "-d | --directory : Instance home directory. It is usually \
+  echo "-i | --instance : Instance home directory. It is usually \
 /home/db2inst1"
   echo "-h | --help : Shows the current documentation."
   echo "-v | --verbose : Executes the script in verbose mode."
   echo "-V | --version : Shows the current version of this script."
 }
 
+# Variable to control the flow execution. Prevent Spaghetti code.
+CONTINUE=true
+
+# Nagios return codes
+OK=0
+WARNING=1
+CRITICAL=2
+UNKNOWN=3
+# This is the returned code.
+RETURN=$UNKNOWN
+
+# Nagios Output
+# Text output 80 chars | Optional Perf Data Line 1
+# Long text Line 1
+# Long text Line 2 | Optional Perf Data Line 2
+# Optional Perf Data Line 3
+OUTPUT=
+
 APPL_NAME=$0
 
 if [ $# == 0 ] ; then
   print_usage $APPL_NAME
-  exit $UNKNOWN
+  RETURN=$UNKNOWN
+  CONTINUE=false
 fi
 
 # The following requieres GNU getopt. See the following discusion.
 # http://stackoverflow.com/questions/402377/using-getopts-in-bash-shell-script-to-get-long-and-short-command-line-options
 
-TEMP=`getopt -o hVvd: --long help,version,verbose,directory \
-             -n '$APPL_NAME' -- "$@"`
+TEMP=`getopt -o hVvi: --long help,version,verbose,instance \
+             -n $APPL_NAME -- "$@"`
 
 if [ $? != 0 ] ; then
   print_usage $APPL_NAME
-  exit $UNKNOWN
+  RETURN=$UNKNOWN
+  CONTINUE=false
 fi
 
-# Note the quotes around `$TEMP': they are essential!
-eval set -- "$TEMP"
+if [[ $CONTINUE == true ]] ; then
+  # Note the quotes around $TEMP: they are essential!
+  eval set -- "$TEMP"
 
-HELP=false
-VERSION=false
-VERBOSE=false
-INSTANCE_HOME=
-while true; do
-  case "$1" in
-    -h | --help ) HELP=true; shift ;;
-    -V | --version ) VERSION=true; shift ;;
-    -v | --verbose ) VERBOSE=true; shift ;;
-    -d | --directory ) INSTANCE_HOME="$2"; shift 2 ;;
-    -- ) shift; break ;;
-    * ) break ;;
-  esac
-done
+  HELP=false
+  VERSION=false
+  VERBOSE=false
+  INSTANCE_HOME=
+  while true; do
+    case "$1" in
+      -h | --help ) HELP=true; shift ;;
+      -V | --version ) VERSION=true; shift ;;
+      -v | --verbose ) VERBOSE=true; shift ;;
+      -i | --instance ) INSTANCE_HOME="$2"; shift 2 ;;
+      -- ) shift; break ;;
+      * ) break ;;
+    esac
+  done
 
-if [[ $VERBOSE = true ]] ; then
-  echo help:$HELP, version:$VERSION, verbose:$VERBOSE, directory:$INSTANCE_HOME
+  if [[ $CONTINUE == true && $VERBOSE == true ]] ; then
+    echo help:$HELP, version:$VERSION, verbose:$VERBOSE, directory:$INSTANCE_HOME
+  fi
+
+  if [[ $CONTINUE == true && $HELP == true ]] ; then
+    print_help $APPL_NAME
+    RETURN=$UNKNOWN
+    CONTINUE=false
+  fi
+
+  if [[ $CONTINUE == true && $VERSION == true ]] ; then
+    print_revision $APPL_NAME
+    RETURN=$UNKNOWN
+    CONTINUE=false
+  fi
+
+  if [[ $CONTINUE == true && $INSTANCE_HOME == "" ]] ; then
+    print_usage $APPL_NAME
+    RETURN=$UNKNOWN
+	CONTINUE=false
+  fi
+
+  if [[ $CONTINUE == true ]] ; then
+    # Load the DB2 profile.
+    . $INSTANCE_HOME/sqllib/db2profile
+
+    # Gets the service name configure in the instance. It could be a text or a number.
+    SVCNAME=`db2 get dbm cfg | grep SVCENAME | awk -F= '{print $2}' | sed "s/^[ \t]*//"`
+    # Copies the value in portnum, but checks later.
+    PORTNUM=$SVCNAME
+
+    if ! [[ $SVCNAME =~ ^[0-9]+$ ]] ; then
+      # SVCNAME is a text, thus replace portnum.
+      # FIXME Real Regular expression should be "^$SVCNAME[ \t]"
+      REGEXP="^$SVCNAME "
+      PORTNUM=`grep -P $REGEXP /etc/services | awk '{print $2}' | awk -F/ '{print $1}'`
+    fi
+
+    # Checks if the port has a active service associated.
+    PROC=`netstat -na | grep $PORTNUM | wc -l`
+
+    if [[ $PROC -eq "0" ]] ; then
+      OUTPUT="DB2 - Instance is down."
+      RETURN=$STATE_CRITICAL
+    else
+      OUTPUT="DB2 - Instance is up."
+      RETURN=$STATE_OK
+    fi
+  fi
 fi
 
-if [[ $HELP = true ]] ; then
-  print_help $APPL_NAME
-  exit $UNKNOWN
+# Prints the output.
+if [[ $OUTPUT == "" ]] ; then
+  OUTPUT="Note: The test was not executed."
 fi
-
-if [[ $VERSION = true ]] ; then
-  print_revision $APPL_NAME
-  exit $UNKNOWN
+echo $OUTPUT
+# Returns the error code.
+if [[ $VERBOSE == true ]] ; then
+  echo Return code: $RETURN
 fi
-
-if [[ $INSTANCE_HOME == "" ]] ; then
-  print_usage $APPL_NAME
-  exit $UNKNOWN
-fi
-
-# Load the DB2 profile.
-. $INSTANCE_HOME/sqllib/db2profile
-
-# Gets the service name configure in the instance. It could be a text or a number.
-SVCNAME=`db2 get dbm cfg | grep SVCENAME | awk -F= '{print $2}' | sed "s/^[ \t]*//"`
-# Copies the value in portnum, but checks later.
-PORTNUM=$SVCNAME
-
-if ! [[ $SVCNAME =~ ^[0-9]+$ ]] ; then
-  # SVCNAME is a text, thus replace portnum.
-  # FIXME Real Regular expression should be "^$SVCNAME[ \t]"
-  REGEXP="^$SVCNAME "
-  PORTNUM=`grep -P $REGEXP /etc/services | awk '{print $2}' | awk -F/ '{print $1}'`
-fi
-
-# Checks if the port has a active service associated.
-PROC=`netstat -na | grep $PORTNUM | wc -l`
-
-if [[ $PROC -eq "0" ]] ; then
-  echo "DB2 - Instance is down."   
-  exit $STATE_CRITICAL
-else
-  echo "DB2 - Instance is up."   
-  exit $STATE_OK
-fi
+exit $RETURN
