Size MB

diff --git a/check_tablespace_size b/check_tablespace_size
--- a/check_tablespace_size
+++ b/check_tablespace_size
@@ -394,21 +394,21 @@ if [[ $CONTINUE == true ]] ; then
   
   # Performancee data
   if [[ $TABLESPACE_NAME != "" ]] ; then
-    COMMAND_SIZE="db2 -x select TBSP_USED_SIZE_KB from sysibmadm.TBSP_UTILIZATION where TBSP_NAME = '$TABLESPACE_NAME'"
+    COMMAND_SIZE="db2 -x select TBSP_USED_SIZE_KB / 1024 from sysibmadm.TBSP_UTILIZATION where TBSP_NAME = '$TABLESPACE_NAME'"
   else
-    COMMAND_SIZE="db2 -x select TBSP_USED_SIZE_KB from sysibmadm.TBSP_UTILIZATION where TBSP_ID = $TABLESPACE_ID"
+    COMMAND_SIZE="db2 -x select TBSP_USED_SIZE_KB / 1024 from sysibmadm.TBSP_UTILIZATION where TBSP_ID = $TABLESPACE_ID"
   fi
   if [[ $VERBOSE -ge 2 ]] ; then
     echo "COMMAND: $COMMAND_SIZE"
   fi
-  KBYTES=`db2 connect to $DATABASE_NAME > /dev/null ; if [[ $? -ne 0 ]] ; then echo "error" ; fi ; $COMMAND_SIZE | awk '{print $1}' ; db2 connect reset > /dev/null`
+  TB_SIZE=`db2 connect to $DATABASE_NAME > /dev/null ; if [[ $? -ne 0 ]] ; then echo "error" ; fi ; $COMMAND_SIZE | awk '{print $1}' ; db2 connect reset > /dev/null`
 
   if [[ $VERBOSE -ge 3 ]] ; then
     echo "RESULT:'$KBYTES'"
   fi
 
   if [[ $KBYTES != "error" ]] ; then
-    PERFORMANCE="'Tablespace $TABLESPACE_NAME$TABLESPACE_ID'=${KBYTES}KB;;;0 "
+    PERFORMANCE="'Tablespace $TABLESPACE_NAME$TABLESPACE_ID'=${KBYTES};;;0 "
   fi
   # TODO As part of the performance, display the status (backup pending, restore pending, etc.(
 fi
